//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoopbackTransport.Configuration
{
    using System;
    using System.Configuration;
    using System.ServiceModel;
    using System.ServiceModel.Channels;
    using System.ServiceModel.Configuration;
    
    internal class LoopbackTransportConfigurationStrings {
        
        internal const string ManualAddressing = "manualAddressing";

        internal const string CopyMessageProperties = "copyMessageProperties";
    }
}
