//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoopbackTransport.Configuration
{
    using System;
    using System.Configuration;
    using System.ServiceModel;
    using System.ServiceModel.Channels;
    using System.ServiceModel.Configuration;
    
    // Please initialize default values to these fields
    internal class LoopbackTransportDefaults {
        
        /* transport supports per-message destination endpoint address overriding, loopback addresses are dummy anyway */
        internal const Boolean DefaultManualAddressing = true;

        internal const Boolean DefaultCopyMessageProperties = true;
    }
}
